config/routes.rb
Rails.application.routes.draw do

  resources :articles do
  	resources :comments
  end

  root 'welcome#index'

  devise_for :users
  resources :users


end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many  :comments, dependent: :destroy
	belongs_to :user 
	validates :title, presence: true,
						length: { minimum: 5 }
	validates :text, presence: true,
						length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController


	def index
		@articles = Article.all
	end

	def show
		@article = Article.find(params[:id])
	end

	def new
		@article = Article.new
	end

	def edit
		@article = Article.find(params[:id])
	end


	def create
		@article = Article.new(article_params)

		if @article.save
		redirect_to @article
		else
			render 'new'
		end
	end

	def update
		@article = Article.find(params[:id])

		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy 
		@article = Article.find(params[:id])
		@article.destroy

		redirect_to articles_path
	end

	private 
	def article_params
		params.require(:article).permit(:title, :text)
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
	def create
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(comment_params)
		redirect_to article_path(@article)
	end

	private
		def comment_params
			params.require(:comment).permit(:commenter, :body)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
	
	<% if @article.errors.any? %>
		<div id="error_explanation">
		<h2>
			<%= pluralize(@article.errors.count, "error") %> 
			Prevented you from submitting the article! 
		</h2>
		<ul>
			<% @article.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
		</div>
	<% end %>
<div class="panel-body">
	<p class="form-group">
		<%= f.label :name %><br>
		<%= f.text_field :name, class: "form-control" %>
	</p>
	<p class="form-group">
		<%= f.label :title %><br>
		<%= f.text_field :title, class: "form-control" %>
	</p>
	<p class="form-group">
		<%= f.label :text %> <br>
		<%= f.text_area :text, class: "form-control" %> 
	</p>
	<p>
		<%= f.submit class: "btn btn-primary" %>
	</p>
<% end %>
</div>

app/views/articles/edit.html.erb
<div class="container-fluid">
<h1>Edit Article</h1>

<%= render 'form' %>

<div class="panel-footer">
<%= link_to 'Back', articles_path %>
</div>
</div>

app/views/articles/index.html.erb
<div class="container-fluid">
<h1>All Articles</h1>
<div class="new-btn"> <%= link_to 'New article', new_article_path, class: "btn btn-primary" %></div>
<table class="table">
	<tr>
		<th>Title</th>
		<th>Text</th>
		<th>Author</th>
		<th colspan="2">Actions</th>
	</tr>

	<% @articles.each do |article| %>
	<tr>
		<td><%= article.title %></td>
		<td><%= article.text %></td>
		<td><%= article.name %></td>
		<td><%= link_to 'Show', article_path(article), class: "btn btn-primary" %></td>
		<td><%= link_to 'Edit', edit_article_path(article), class: "btn btn-success" %></td>
		<td><%= link_to 'Delete', article_path(article),
				method: :delete,
				data: { confirm: 'Are you sure?'}, class: "btn btn-danger" %></td>
	</tr>
	<% end %>
</table>

<%= link_to 'Home', root_path, class: "btn btn-default" %>

</div>

app/views/articles/new.html.erb
<div class="container-fluid"><h1>New Article</h1>

<%= render 'form' %>

<div class="panel-footer">
<%= link_to 'Back', articles_path, class: "btn btn-link" %>
</div>
</div>

app/views/articles/show.html.erb
<div class="container-fluid">
<h1>Look at the results!</h1>
<p>
	<strong>Title:</strong>
	<%= @article.title %> 
</p>

<p>
	<strong>Text:</strong>
	<%= @article.text %> 
</p>
<p>
	<strong>Text:</strong>
	<%= @article.name %> 
</p>

<h2>Comments:</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<div class="panel-footer">	
<%= link_to 'Edit', edit_article_path(@article) %>
<%= link_to 'Back', articles_path, class: "btn-link" %>
</div>
</div>

app/views/comments/_comment.html.erb
	<p>
		<strong>Commenter:</strong>
		<%= comment.commenter %>
	</p>
	<p>
		<strong>Comment:</strong>
		<%= comment.body %>
	</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
	<p class="form-group">
		<%= f.label :commenter %><br>
		<%= f.text_field :commenter, class:"form-control" %>
	</p>
	<p class="form-group">
		<%= f.label :body %><br>
		<%= f.text_area :body, class: "form-control" %>
	</p>
	<p class="form-group"> 
	<%= f.submit class: "btn btn-primary" %>		
	</p>
<% end %>

app/views/layouts/_footer.html.erb
     <!-- FOOTER -->
      <footer class="footer">
           <div class="container">
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>&copy; 2014 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
    </div><!-- /.container -->
    </footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">Blogging</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if user_signed_in? %>     
        <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        <li><%= link_to "Account Settings", edit_user_registration_path %></li>
        <% else %>             
        <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
        </div>
    
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/users/_form.html.erb
<div class="container-fluid">
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class:"btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<div class="header-bg">
<div class="jumbotron">
<h1>Start Blogging!</h1>
    <p>
    <% if user_signed_in? %>
    <%= link_to "New Blog", new_article_path , class: "btn btn-primary btn-lg" %>
    <%= link_to "View All Posts", articles_path , class: "btn btn-default btn-lg" %>
    <% else %>      
    </p>

<p>
<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
<%= link_to "Log In", new_user_session_path, class: "btn btn-default btn-lg" %>
</p>
    <% end %>
</div>
</div>